server.port: 8082

spring:
  application.name: payment-service
  output.ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shop}
    username: ${DB_USERNAME:shop}
    password: ${DB_PASSWORD:shop}
    continue-on-error: false
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false